language: cpp

sudo: required
dist: trusty
osx_image: xcode7.3
cache: ccache

# Travis CI VM OSs
os:
    - linux
    - osx

# Travis CI build matrix components
compiler:
    - gcc
    - clang

env:
    - TRAVIS_BUILD_TYPE=Debug
    - TRAVIS_BUILD_TYPE=Release

before_script:
    # Run CMake
    - mkdir build
    - cd build
    - cmake -DBUILD_TESTING:BOOL=ON -DCMAKE_BUILD_TYPE=${TRAVIS_BUILD_TYPE} ..

script:
    - make
    - make test
