sudo: required
dist: trusty
osx_image: xcode7.3
language: cpp
cache: ccache

compiler:
  - gcc
  - clang

os: 
  - linux
  - os: osx
env:
  - TRAVIS_BUILD_TYPE=Debug
  - TRAVIS_BUILD_TYPE=Release
  
before_script:
  # Build and install YCM
  - git clone https://github.com/robotology/ycm.git
  - cd ycm
  - mkdir build
  - cd build
  - cmake ..
  - make
  - sudo make install
  - cd ../..
  # Run CMake
  - mkdir build
  - cd build
  - cmake -DBUILD_TESTING:BOOL=ON -DCMAKE_BUILD_TYPE=${TRAVIS_BUILD_TYPE} ..
  
script: 
  - make
  - make test
